### ISSUE TITLE
Evaluate and include a internationalization module

### ISSUE THREAD

**Issue by thomascube** [roundcube-next/roundcube-shell#2]
A library shall be evaluated to add internationalization functionality to the Roundcube Shell. This preferably is integrated as an Ember service and made available to all apps and templates.

Apps will provide localization files containing all the localized texts used within. The localized labels shall be accessible under distinct namespaces equal to the app name. Example: "mail::subject"

Candidates:
- [ember-i18n](https://github.com/jamesarosen/ember-i18n)
- [i18next](http://i18next.com)

**Comment by adityab** [comment]
I evaluated both and felt that `ember-i18n` was the better choice in terms of ease of use.

Now, it's fallback mechanism for unsupported locales leaves much to be desired - for example `de-AT` will fall back to `de`, but if the latter is not present, it will not look at `en`, and instead throw "missing label".

Therefore, I had to override that part in an initializer, in addition to adding some logic to look under addon directories to merge all of their translations into one for each language.

How this works is now described in the [new wiki page](https://github.com/roundcube-next/roundcube-shell/wiki/Translating). Cheers!
